using FluentMigrator;

namespace DbDeployment.Migrations.Remittance
{
    [Migration(2026022402)]
    public class InsertCountries : Migration
    {
        public override void Up()
        {
            // Insert all world countries
            var countries = new[]
            {
                new { Name = "Afghanistan", Iso2 = "AF", Iso3 = "AFG", Phone = "+93", Currency = "AFN", CurrencyName = "Afghan Afghani" },
                new { Name = "Albania", Iso2 = "AL", Iso3 = "ALB", Phone = "+355", Currency = "ALL", CurrencyName = "Albanian Lek" },
                new { Name = "Algeria", Iso2 = "DZ", Iso3 = "DZA", Phone = "+213", Currency = "DZD", CurrencyName = "Algerian Dinar" },
                new { Name = "Andorra", Iso2 = "AD", Iso3 = "AND", Phone = "+376", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Angola", Iso2 = "AO", Iso3 = "AGO", Phone = "+244", Currency = "AOA", CurrencyName = "Angolan Kwanza" },
                new { Name = "Antigua and Barbuda", Iso2 = "AG", Iso3 = "ATG", Phone = "+1-268", Currency = "XCD", CurrencyName = "East Caribbean Dollar" },
                new { Name = "Argentina", Iso2 = "AR", Iso3 = "ARG", Phone = "+54", Currency = "ARS", CurrencyName = "Argentine Peso" },
                new { Name = "Armenia", Iso2 = "AM", Iso3 = "ARM", Phone = "+374", Currency = "AMD", CurrencyName = "Armenian Dram" },
                new { Name = "Australia", Iso2 = "AU", Iso3 = "AUS", Phone = "+61", Currency = "AUD", CurrencyName = "Australian Dollar" },
                new { Name = "Austria", Iso2 = "AT", Iso3 = "AUT", Phone = "+43", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Azerbaijan", Iso2 = "AZ", Iso3 = "AZE", Phone = "+994", Currency = "AZN", CurrencyName = "Azerbaijani Manat" },
                new { Name = "Bahamas", Iso2 = "BS", Iso3 = "BHS", Phone = "+1-242", Currency = "BSD", CurrencyName = "Bahamian Dollar" },
                new { Name = "Bahrain", Iso2 = "BH", Iso3 = "BHR", Phone = "+973", Currency = "BHD", CurrencyName = "Bahraini Dinar" },
                new { Name = "Bangladesh", Iso2 = "BD", Iso3 = "BGD", Phone = "+880", Currency = "BDT", CurrencyName = "Bangladeshi Taka" },
                new { Name = "Barbados", Iso2 = "BB", Iso3 = "BRB", Phone = "+1-246", Currency = "BBD", CurrencyName = "Barbadian Dollar" },
                new { Name = "Belarus", Iso2 = "BY", Iso3 = "BLR", Phone = "+375", Currency = "BYN", CurrencyName = "Belarusian Ruble" },
                new { Name = "Belgium", Iso2 = "BE", Iso3 = "BEL", Phone = "+32", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Belize", Iso2 = "BZ", Iso3 = "BLZ", Phone = "+501", Currency = "BZD", CurrencyName = "Belize Dollar" },
                new { Name = "Benin", Iso2 = "BJ", Iso3 = "BEN", Phone = "+229", Currency = "XOF", CurrencyName = "West African CFA Franc" },
                new { Name = "Bhutan", Iso2 = "BT", Iso3 = "BTN", Phone = "+975", Currency = "BTN", CurrencyName = "Bhutanese Ngultrum" },
                new { Name = "Bolivia", Iso2 = "BO", Iso3 = "BOL", Phone = "+591", Currency = "BOB", CurrencyName = "Bolivian Boliviano" },
                new { Name = "Bosnia and Herzegovina", Iso2 = "BA", Iso3 = "BIH", Phone = "+387", Currency = "BAM", CurrencyName = "Bosnia-Herzegovina Convertible Mark" },
                new { Name = "Botswana", Iso2 = "BW", Iso3 = "BWA", Phone = "+267", Currency = "BWP", CurrencyName = "Botswanan Pula" },
                new { Name = "Brazil", Iso2 = "BR", Iso3 = "BRA", Phone = "+55", Currency = "BRL", CurrencyName = "Brazilian Real" },
                new { Name = "Brunei", Iso2 = "BN", Iso3 = "BRN", Phone = "+673", Currency = "BND", CurrencyName = "Brunei Dollar" },
                new { Name = "Bulgaria", Iso2 = "BG", Iso3 = "BGR", Phone = "+359", Currency = "BGN", CurrencyName = "Bulgarian Lev" },
                new { Name = "Burkina Faso", Iso2 = "BF", Iso3 = "BFA", Phone = "+226", Currency = "XOF", CurrencyName = "West African CFA Franc" },
                new { Name = "Burundi", Iso2 = "BI", Iso3 = "BDI", Phone = "+257", Currency = "BIF", CurrencyName = "Burundian Franc" },
                new { Name = "Cabo Verde", Iso2 = "CV", Iso3 = "CPV", Phone = "+238", Currency = "CVE", CurrencyName = "Cape Verdean Escudo" },
                new { Name = "Cambodia", Iso2 = "KH", Iso3 = "KHM", Phone = "+855", Currency = "KHR", CurrencyName = "Cambodian Riel" },
                new { Name = "Cameroon", Iso2 = "CM", Iso3 = "CMR", Phone = "+237", Currency = "XAF", CurrencyName = "Central African CFA Franc" },
                new { Name = "Canada", Iso2 = "CA", Iso3 = "CAN", Phone = "+1", Currency = "CAD", CurrencyName = "Canadian Dollar" },
                new { Name = "Central African Republic", Iso2 = "CF", Iso3 = "CAF", Phone = "+236", Currency = "XAF", CurrencyName = "Central African CFA Franc" },
                new { Name = "Chad", Iso2 = "TD", Iso3 = "TCD", Phone = "+235", Currency = "XAF", CurrencyName = "Central African CFA Franc" },
                new { Name = "Chile", Iso2 = "CL", Iso3 = "CHL", Phone = "+56", Currency = "CLP", CurrencyName = "Chilean Peso" },
                new { Name = "China", Iso2 = "CN", Iso3 = "CHN", Phone = "+86", Currency = "CNY", CurrencyName = "Chinese Yuan" },
                new { Name = "Colombia", Iso2 = "CO", Iso3 = "COL", Phone = "+57", Currency = "COP", CurrencyName = "Colombian Peso" },
                new { Name = "Comoros", Iso2 = "KM", Iso3 = "COM", Phone = "+269", Currency = "KMF", CurrencyName = "Comorian Franc" },
                new { Name = "Congo (DRC)", Iso2 = "CD", Iso3 = "COD", Phone = "+243", Currency = "CDF", CurrencyName = "Congolese Franc" },
                new { Name = "Congo (Republic)", Iso2 = "CG", Iso3 = "COG", Phone = "+242", Currency = "XAF", CurrencyName = "Central African CFA Franc" },
                new { Name = "Costa Rica", Iso2 = "CR", Iso3 = "CRI", Phone = "+506", Currency = "CRC", CurrencyName = "Costa Rican Colon" },
                new { Name = "Croatia", Iso2 = "HR", Iso3 = "HRV", Phone = "+385", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Cuba", Iso2 = "CU", Iso3 = "CUB", Phone = "+53", Currency = "CUP", CurrencyName = "Cuban Peso" },
                new { Name = "Cyprus", Iso2 = "CY", Iso3 = "CYP", Phone = "+357", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Czech Republic", Iso2 = "CZ", Iso3 = "CZE", Phone = "+420", Currency = "CZK", CurrencyName = "Czech Koruna" },
                new { Name = "Denmark", Iso2 = "DK", Iso3 = "DNK", Phone = "+45", Currency = "DKK", CurrencyName = "Danish Krone" },
                new { Name = "Djibouti", Iso2 = "DJ", Iso3 = "DJI", Phone = "+253", Currency = "DJF", CurrencyName = "Djiboutian Franc" },
                new { Name = "Dominica", Iso2 = "DM", Iso3 = "DMA", Phone = "+1-767", Currency = "XCD", CurrencyName = "East Caribbean Dollar" },
                new { Name = "Dominican Republic", Iso2 = "DO", Iso3 = "DOM", Phone = "+1-809", Currency = "DOP", CurrencyName = "Dominican Peso" },
                new { Name = "Ecuador", Iso2 = "EC", Iso3 = "ECU", Phone = "+593", Currency = "USD", CurrencyName = "US Dollar" },
                new { Name = "Egypt", Iso2 = "EG", Iso3 = "EGY", Phone = "+20", Currency = "EGP", CurrencyName = "Egyptian Pound" },
                new { Name = "El Salvador", Iso2 = "SV", Iso3 = "SLV", Phone = "+503", Currency = "USD", CurrencyName = "US Dollar" },
                new { Name = "Equatorial Guinea", Iso2 = "GQ", Iso3 = "GNQ", Phone = "+240", Currency = "XAF", CurrencyName = "Central African CFA Franc" },
                new { Name = "Eritrea", Iso2 = "ER", Iso3 = "ERI", Phone = "+291", Currency = "ERN", CurrencyName = "Eritrean Nakfa" },
                new { Name = "Estonia", Iso2 = "EE", Iso3 = "EST", Phone = "+372", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Eswatini", Iso2 = "SZ", Iso3 = "SWZ", Phone = "+268", Currency = "SZL", CurrencyName = "Swazi Lilangeni" },
                new { Name = "Ethiopia", Iso2 = "ET", Iso3 = "ETH", Phone = "+251", Currency = "ETB", CurrencyName = "Ethiopian Birr" },
                new { Name = "Fiji", Iso2 = "FJ", Iso3 = "FJI", Phone = "+679", Currency = "FJD", CurrencyName = "Fijian Dollar" },
                new { Name = "Finland", Iso2 = "FI", Iso3 = "FIN", Phone = "+358", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "France", Iso2 = "FR", Iso3 = "FRA", Phone = "+33", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Gabon", Iso2 = "GA", Iso3 = "GAB", Phone = "+241", Currency = "XAF", CurrencyName = "Central African CFA Franc" },
                new { Name = "Gambia", Iso2 = "GM", Iso3 = "GMB", Phone = "+220", Currency = "GMD", CurrencyName = "Gambian Dalasi" },
                new { Name = "Georgia", Iso2 = "GE", Iso3 = "GEO", Phone = "+995", Currency = "GEL", CurrencyName = "Georgian Lari" },
                new { Name = "Germany", Iso2 = "DE", Iso3 = "DEU", Phone = "+49", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Ghana", Iso2 = "GH", Iso3 = "GHA", Phone = "+233", Currency = "GHS", CurrencyName = "Ghanaian Cedi" },
                new { Name = "Greece", Iso2 = "GR", Iso3 = "GRC", Phone = "+30", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Grenada", Iso2 = "GD", Iso3 = "GRD", Phone = "+1-473", Currency = "XCD", CurrencyName = "East Caribbean Dollar" },
                new { Name = "Guatemala", Iso2 = "GT", Iso3 = "GTM", Phone = "+502", Currency = "GTQ", CurrencyName = "Guatemalan Quetzal" },
                new { Name = "Guinea", Iso2 = "GN", Iso3 = "GIN", Phone = "+224", Currency = "GNF", CurrencyName = "Guinean Franc" },
                new { Name = "Guinea-Bissau", Iso2 = "GW", Iso3 = "GNB", Phone = "+245", Currency = "XOF", CurrencyName = "West African CFA Franc" },
                new { Name = "Guyana", Iso2 = "GY", Iso3 = "GUY", Phone = "+592", Currency = "GYD", CurrencyName = "Guyanese Dollar" },
                new { Name = "Haiti", Iso2 = "HT", Iso3 = "HTI", Phone = "+509", Currency = "HTG", CurrencyName = "Haitian Gourde" },
                new { Name = "Honduras", Iso2 = "HN", Iso3 = "HND", Phone = "+504", Currency = "HNL", CurrencyName = "Honduran Lempira" },
                new { Name = "Hungary", Iso2 = "HU", Iso3 = "HUN", Phone = "+36", Currency = "HUF", CurrencyName = "Hungarian Forint" },
                new { Name = "Iceland", Iso2 = "IS", Iso3 = "ISL", Phone = "+354", Currency = "ISK", CurrencyName = "Icelandic Krona" },
                new { Name = "India", Iso2 = "IN", Iso3 = "IND", Phone = "+91", Currency = "INR", CurrencyName = "Indian Rupee" },
                new { Name = "Indonesia", Iso2 = "ID", Iso3 = "IDN", Phone = "+62", Currency = "IDR", CurrencyName = "Indonesian Rupiah" },
                new { Name = "Iran", Iso2 = "IR", Iso3 = "IRN", Phone = "+98", Currency = "IRR", CurrencyName = "Iranian Rial" },
                new { Name = "Iraq", Iso2 = "IQ", Iso3 = "IRQ", Phone = "+964", Currency = "IQD", CurrencyName = "Iraqi Dinar" },
                new { Name = "Ireland", Iso2 = "IE", Iso3 = "IRL", Phone = "+353", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Israel", Iso2 = "IL", Iso3 = "ISR", Phone = "+972", Currency = "ILS", CurrencyName = "Israeli New Shekel" },
                new { Name = "Italy", Iso2 = "IT", Iso3 = "ITA", Phone = "+39", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Ivory Coast", Iso2 = "CI", Iso3 = "CIV", Phone = "+225", Currency = "XOF", CurrencyName = "West African CFA Franc" },
                new { Name = "Jamaica", Iso2 = "JM", Iso3 = "JAM", Phone = "+1-876", Currency = "JMD", CurrencyName = "Jamaican Dollar" },
                new { Name = "Japan", Iso2 = "JP", Iso3 = "JPN", Phone = "+81", Currency = "JPY", CurrencyName = "Japanese Yen" },
                new { Name = "Jordan", Iso2 = "JO", Iso3 = "JOR", Phone = "+962", Currency = "JOD", CurrencyName = "Jordanian Dinar" },
                new { Name = "Kazakhstan", Iso2 = "KZ", Iso3 = "KAZ", Phone = "+7", Currency = "KZT", CurrencyName = "Kazakhstani Tenge" },
                new { Name = "Kenya", Iso2 = "KE", Iso3 = "KEN", Phone = "+254", Currency = "KES", CurrencyName = "Kenyan Shilling" },
                new { Name = "Kiribati", Iso2 = "KI", Iso3 = "KIR", Phone = "+686", Currency = "AUD", CurrencyName = "Australian Dollar" },
                new { Name = "Kuwait", Iso2 = "KW", Iso3 = "KWT", Phone = "+965", Currency = "KWD", CurrencyName = "Kuwaiti Dinar" },
                new { Name = "Kyrgyzstan", Iso2 = "KG", Iso3 = "KGZ", Phone = "+996", Currency = "KGS", CurrencyName = "Kyrgystani Som" },
                new { Name = "Laos", Iso2 = "LA", Iso3 = "LAO", Phone = "+856", Currency = "LAK", CurrencyName = "Lao Kip" },
                new { Name = "Latvia", Iso2 = "LV", Iso3 = "LVA", Phone = "+371", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Lebanon", Iso2 = "LB", Iso3 = "LBN", Phone = "+961", Currency = "LBP", CurrencyName = "Lebanese Pound" },
                new { Name = "Lesotho", Iso2 = "LS", Iso3 = "LSO", Phone = "+266", Currency = "LSL", CurrencyName = "Lesotho Loti" },
                new { Name = "Liberia", Iso2 = "LR", Iso3 = "LBR", Phone = "+231", Currency = "LRD", CurrencyName = "Liberian Dollar" },
                new { Name = "Libya", Iso2 = "LY", Iso3 = "LBY", Phone = "+218", Currency = "LYD", CurrencyName = "Libyan Dinar" },
                new { Name = "Liechtenstein", Iso2 = "LI", Iso3 = "LIE", Phone = "+423", Currency = "CHF", CurrencyName = "Swiss Franc" },
                new { Name = "Lithuania", Iso2 = "LT", Iso3 = "LTU", Phone = "+370", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Luxembourg", Iso2 = "LU", Iso3 = "LUX", Phone = "+352", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Madagascar", Iso2 = "MG", Iso3 = "MDG", Phone = "+261", Currency = "MGA", CurrencyName = "Malagasy Ariary" },
                new { Name = "Malawi", Iso2 = "MW", Iso3 = "MWI", Phone = "+265", Currency = "MWK", CurrencyName = "Malawian Kwacha" },
                new { Name = "Malaysia", Iso2 = "MY", Iso3 = "MYS", Phone = "+60", Currency = "MYR", CurrencyName = "Malaysian Ringgit" },
                new { Name = "Maldives", Iso2 = "MV", Iso3 = "MDV", Phone = "+960", Currency = "MVR", CurrencyName = "Maldivian Rufiyaa" },
                new { Name = "Mali", Iso2 = "ML", Iso3 = "MLI", Phone = "+223", Currency = "XOF", CurrencyName = "West African CFA Franc" },
                new { Name = "Malta", Iso2 = "MT", Iso3 = "MLT", Phone = "+356", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Marshall Islands", Iso2 = "MH", Iso3 = "MHL", Phone = "+692", Currency = "USD", CurrencyName = "US Dollar" },
                new { Name = "Mauritania", Iso2 = "MR", Iso3 = "MRT", Phone = "+222", Currency = "MRU", CurrencyName = "Mauritanian Ouguiya" },
                new { Name = "Mauritius", Iso2 = "MU", Iso3 = "MUS", Phone = "+230", Currency = "MUR", CurrencyName = "Mauritian Rupee" },
                new { Name = "Mexico", Iso2 = "MX", Iso3 = "MEX", Phone = "+52", Currency = "MXN", CurrencyName = "Mexican Peso" },
                new { Name = "Micronesia", Iso2 = "FM", Iso3 = "FSM", Phone = "+691", Currency = "USD", CurrencyName = "US Dollar" },
                new { Name = "Moldova", Iso2 = "MD", Iso3 = "MDA", Phone = "+373", Currency = "MDL", CurrencyName = "Moldovan Leu" },
                new { Name = "Monaco", Iso2 = "MC", Iso3 = "MCO", Phone = "+377", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Mongolia", Iso2 = "MN", Iso3 = "MNG", Phone = "+976", Currency = "MNT", CurrencyName = "Mongolian Tugrik" },
                new { Name = "Montenegro", Iso2 = "ME", Iso3 = "MNE", Phone = "+382", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Morocco", Iso2 = "MA", Iso3 = "MAR", Phone = "+212", Currency = "MAD", CurrencyName = "Moroccan Dirham" },
                new { Name = "Mozambique", Iso2 = "MZ", Iso3 = "MOZ", Phone = "+258", Currency = "MZN", CurrencyName = "Mozambican Metical" },
                new { Name = "Myanmar", Iso2 = "MM", Iso3 = "MMR", Phone = "+95", Currency = "MMK", CurrencyName = "Myanmar Kyat" },
                new { Name = "Namibia", Iso2 = "NA", Iso3 = "NAM", Phone = "+264", Currency = "NAD", CurrencyName = "Namibian Dollar" },
                new { Name = "Nauru", Iso2 = "NR", Iso3 = "NRU", Phone = "+674", Currency = "AUD", CurrencyName = "Australian Dollar" },
                new { Name = "Nepal", Iso2 = "NP", Iso3 = "NPL", Phone = "+977", Currency = "NPR", CurrencyName = "Nepalese Rupee" },
                new { Name = "Netherlands", Iso2 = "NL", Iso3 = "NLD", Phone = "+31", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "New Zealand", Iso2 = "NZ", Iso3 = "NZL", Phone = "+64", Currency = "NZD", CurrencyName = "New Zealand Dollar" },
                new { Name = "Nicaragua", Iso2 = "NI", Iso3 = "NIC", Phone = "+505", Currency = "NIO", CurrencyName = "Nicaraguan Cordoba" },
                new { Name = "Niger", Iso2 = "NE", Iso3 = "NER", Phone = "+227", Currency = "XOF", CurrencyName = "West African CFA Franc" },
                new { Name = "Nigeria", Iso2 = "NG", Iso3 = "NGA", Phone = "+234", Currency = "NGN", CurrencyName = "Nigerian Naira" },
                new { Name = "North Korea", Iso2 = "KP", Iso3 = "PRK", Phone = "+850", Currency = "KPW", CurrencyName = "North Korean Won" },
                new { Name = "North Macedonia", Iso2 = "MK", Iso3 = "MKD", Phone = "+389", Currency = "MKD", CurrencyName = "Macedonian Denar" },
                new { Name = "Norway", Iso2 = "NO", Iso3 = "NOR", Phone = "+47", Currency = "NOK", CurrencyName = "Norwegian Krone" },
                new { Name = "Oman", Iso2 = "OM", Iso3 = "OMN", Phone = "+968", Currency = "OMR", CurrencyName = "Omani Rial" },
                new { Name = "Pakistan", Iso2 = "PK", Iso3 = "PAK", Phone = "+92", Currency = "PKR", CurrencyName = "Pakistani Rupee" },
                new { Name = "Palau", Iso2 = "PW", Iso3 = "PLW", Phone = "+680", Currency = "USD", CurrencyName = "US Dollar" },
                new { Name = "Palestine", Iso2 = "PS", Iso3 = "PSE", Phone = "+970", Currency = "ILS", CurrencyName = "Israeli New Shekel" },
                new { Name = "Panama", Iso2 = "PA", Iso3 = "PAN", Phone = "+507", Currency = "PAB", CurrencyName = "Panamanian Balboa" },
                new { Name = "Papua New Guinea", Iso2 = "PG", Iso3 = "PNG", Phone = "+675", Currency = "PGK", CurrencyName = "Papua New Guinean Kina" },
                new { Name = "Paraguay", Iso2 = "PY", Iso3 = "PRY", Phone = "+595", Currency = "PYG", CurrencyName = "Paraguayan Guarani" },
                new { Name = "Peru", Iso2 = "PE", Iso3 = "PER", Phone = "+51", Currency = "PEN", CurrencyName = "Peruvian Sol" },
                new { Name = "Philippines", Iso2 = "PH", Iso3 = "PHL", Phone = "+63", Currency = "PHP", CurrencyName = "Philippine Peso" },
                new { Name = "Poland", Iso2 = "PL", Iso3 = "POL", Phone = "+48", Currency = "PLN", CurrencyName = "Polish Zloty" },
                new { Name = "Portugal", Iso2 = "PT", Iso3 = "PRT", Phone = "+351", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Qatar", Iso2 = "QA", Iso3 = "QAT", Phone = "+974", Currency = "QAR", CurrencyName = "Qatari Riyal" },
                new { Name = "Romania", Iso2 = "RO", Iso3 = "ROU", Phone = "+40", Currency = "RON", CurrencyName = "Romanian Leu" },
                new { Name = "Russia", Iso2 = "RU", Iso3 = "RUS", Phone = "+7", Currency = "RUB", CurrencyName = "Russian Ruble" },
                new { Name = "Rwanda", Iso2 = "RW", Iso3 = "RWA", Phone = "+250", Currency = "RWF", CurrencyName = "Rwandan Franc" },
                new { Name = "Saint Kitts and Nevis", Iso2 = "KN", Iso3 = "KNA", Phone = "+1-869", Currency = "XCD", CurrencyName = "East Caribbean Dollar" },
                new { Name = "Saint Lucia", Iso2 = "LC", Iso3 = "LCA", Phone = "+1-758", Currency = "XCD", CurrencyName = "East Caribbean Dollar" },
                new { Name = "Saint Vincent and the Grenadines", Iso2 = "VC", Iso3 = "VCT", Phone = "+1-784", Currency = "XCD", CurrencyName = "East Caribbean Dollar" },
                new { Name = "Samoa", Iso2 = "WS", Iso3 = "WSM", Phone = "+685", Currency = "WST", CurrencyName = "Samoan Tala" },
                new { Name = "San Marino", Iso2 = "SM", Iso3 = "SMR", Phone = "+378", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Sao Tome and Principe", Iso2 = "ST", Iso3 = "STP", Phone = "+239", Currency = "STN", CurrencyName = "Sao Tome and Principe Dobra" },
                new { Name = "Saudi Arabia", Iso2 = "SA", Iso3 = "SAU", Phone = "+966", Currency = "SAR", CurrencyName = "Saudi Riyal" },
                new { Name = "Senegal", Iso2 = "SN", Iso3 = "SEN", Phone = "+221", Currency = "XOF", CurrencyName = "West African CFA Franc" },
                new { Name = "Serbia", Iso2 = "RS", Iso3 = "SRB", Phone = "+381", Currency = "RSD", CurrencyName = "Serbian Dinar" },
                new { Name = "Seychelles", Iso2 = "SC", Iso3 = "SYC", Phone = "+248", Currency = "SCR", CurrencyName = "Seychellois Rupee" },
                new { Name = "Sierra Leone", Iso2 = "SL", Iso3 = "SLE", Phone = "+232", Currency = "SLL", CurrencyName = "Sierra Leonean Leone" },
                new { Name = "Singapore", Iso2 = "SG", Iso3 = "SGP", Phone = "+65", Currency = "SGD", CurrencyName = "Singapore Dollar" },
                new { Name = "Slovakia", Iso2 = "SK", Iso3 = "SVK", Phone = "+421", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Slovenia", Iso2 = "SI", Iso3 = "SVN", Phone = "+386", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Solomon Islands", Iso2 = "SB", Iso3 = "SLB", Phone = "+677", Currency = "SBD", CurrencyName = "Solomon Islands Dollar" },
                new { Name = "Somalia", Iso2 = "SO", Iso3 = "SOM", Phone = "+252", Currency = "SOS", CurrencyName = "Somali Shilling" },
                new { Name = "South Africa", Iso2 = "ZA", Iso3 = "ZAF", Phone = "+27", Currency = "ZAR", CurrencyName = "South African Rand" },
                new { Name = "South Korea", Iso2 = "KR", Iso3 = "KOR", Phone = "+82", Currency = "KRW", CurrencyName = "South Korean Won" },
                new { Name = "South Sudan", Iso2 = "SS", Iso3 = "SSD", Phone = "+211", Currency = "SSP", CurrencyName = "South Sudanese Pound" },
                new { Name = "Spain", Iso2 = "ES", Iso3 = "ESP", Phone = "+34", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Sri Lanka", Iso2 = "LK", Iso3 = "LKA", Phone = "+94", Currency = "LKR", CurrencyName = "Sri Lankan Rupee" },
                new { Name = "Sudan", Iso2 = "SD", Iso3 = "SDN", Phone = "+249", Currency = "SDG", CurrencyName = "Sudanese Pound" },
                new { Name = "Suriname", Iso2 = "SR", Iso3 = "SUR", Phone = "+597", Currency = "SRD", CurrencyName = "Surinamese Dollar" },
                new { Name = "Sweden", Iso2 = "SE", Iso3 = "SWE", Phone = "+46", Currency = "SEK", CurrencyName = "Swedish Krona" },
                new { Name = "Switzerland", Iso2 = "CH", Iso3 = "CHE", Phone = "+41", Currency = "CHF", CurrencyName = "Swiss Franc" },
                new { Name = "Syria", Iso2 = "SY", Iso3 = "SYR", Phone = "+963", Currency = "SYP", CurrencyName = "Syrian Pound" },
                new { Name = "Taiwan", Iso2 = "TW", Iso3 = "TWN", Phone = "+886", Currency = "TWD", CurrencyName = "New Taiwan Dollar" },
                new { Name = "Tajikistan", Iso2 = "TJ", Iso3 = "TJK", Phone = "+992", Currency = "TJS", CurrencyName = "Tajikistani Somoni" },
                new { Name = "Tanzania", Iso2 = "TZ", Iso3 = "TZA", Phone = "+255", Currency = "TZS", CurrencyName = "Tanzanian Shilling" },
                new { Name = "Thailand", Iso2 = "TH", Iso3 = "THA", Phone = "+66", Currency = "THB", CurrencyName = "Thai Baht" },
                new { Name = "Timor-Leste", Iso2 = "TL", Iso3 = "TLS", Phone = "+670", Currency = "USD", CurrencyName = "US Dollar" },
                new { Name = "Togo", Iso2 = "TG", Iso3 = "TGO", Phone = "+228", Currency = "XOF", CurrencyName = "West African CFA Franc" },
                new { Name = "Tonga", Iso2 = "TO", Iso3 = "TON", Phone = "+676", Currency = "TOP", CurrencyName = "Tongan Paanga" },
                new { Name = "Trinidad and Tobago", Iso2 = "TT", Iso3 = "TTO", Phone = "+1-868", Currency = "TTD", CurrencyName = "Trinidad and Tobago Dollar" },
                new { Name = "Tunisia", Iso2 = "TN", Iso3 = "TUN", Phone = "+216", Currency = "TND", CurrencyName = "Tunisian Dinar" },
                new { Name = "Turkey", Iso2 = "TR", Iso3 = "TUR", Phone = "+90", Currency = "TRY", CurrencyName = "Turkish Lira" },
                new { Name = "Turkmenistan", Iso2 = "TM", Iso3 = "TKM", Phone = "+993", Currency = "TMT", CurrencyName = "Turkmenistani Manat" },
                new { Name = "Tuvalu", Iso2 = "TV", Iso3 = "TUV", Phone = "+688", Currency = "AUD", CurrencyName = "Australian Dollar" },
                new { Name = "Uganda", Iso2 = "UG", Iso3 = "UGA", Phone = "+256", Currency = "UGX", CurrencyName = "Ugandan Shilling" },
                new { Name = "Ukraine", Iso2 = "UA", Iso3 = "UKR", Phone = "+380", Currency = "UAH", CurrencyName = "Ukrainian Hryvnia" },
                new { Name = "United Arab Emirates", Iso2 = "AE", Iso3 = "ARE", Phone = "+971", Currency = "AED", CurrencyName = "UAE Dirham" },
                new { Name = "United Kingdom", Iso2 = "GB", Iso3 = "GBR", Phone = "+44", Currency = "GBP", CurrencyName = "British Pound" },
                new { Name = "United States", Iso2 = "US", Iso3 = "USA", Phone = "+1", Currency = "USD", CurrencyName = "US Dollar" },
                new { Name = "Uruguay", Iso2 = "UY", Iso3 = "URY", Phone = "+598", Currency = "UYU", CurrencyName = "Uruguayan Peso" },
                new { Name = "Uzbekistan", Iso2 = "UZ", Iso3 = "UZB", Phone = "+998", Currency = "UZS", CurrencyName = "Uzbekistani Som" },
                new { Name = "Vanuatu", Iso2 = "VU", Iso3 = "VUT", Phone = "+678", Currency = "VUV", CurrencyName = "Vanuatu Vatu" },
                new { Name = "Vatican City", Iso2 = "VA", Iso3 = "VAT", Phone = "+379", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Venezuela", Iso2 = "VE", Iso3 = "VEN", Phone = "+58", Currency = "VES", CurrencyName = "Venezuelan Bolivar" },
                new { Name = "Vietnam", Iso2 = "VN", Iso3 = "VNM", Phone = "+84", Currency = "VND", CurrencyName = "Vietnamese Dong" },
                new { Name = "Yemen", Iso2 = "YE", Iso3 = "YEM", Phone = "+967", Currency = "YER", CurrencyName = "Yemeni Rial" },
                new { Name = "Zambia", Iso2 = "ZM", Iso3 = "ZMB", Phone = "+260", Currency = "ZMW", CurrencyName = "Zambian Kwacha" },
                new { Name = "Zimbabwe", Iso2 = "ZW", Iso3 = "ZWE", Phone = "+263", Currency = "ZWL", CurrencyName = "Zimbabwean Dollar" },
                // Territories & special entries commonly used in remittance
                new { Name = "Hong Kong", Iso2 = "HK", Iso3 = "HKG", Phone = "+852", Currency = "HKD", CurrencyName = "Hong Kong Dollar" },
                new { Name = "Macau", Iso2 = "MO", Iso3 = "MAC", Phone = "+853", Currency = "MOP", CurrencyName = "Macanese Pataca" },
                new { Name = "Puerto Rico", Iso2 = "PR", Iso3 = "PRI", Phone = "+1-787", Currency = "USD", CurrencyName = "US Dollar" },
                new { Name = "Kosovo", Iso2 = "XK", Iso3 = "XKX", Phone = "+383", Currency = "EUR", CurrencyName = "Euro" },
                new { Name = "Curacao", Iso2 = "CW", Iso3 = "CUW", Phone = "+599", Currency = "ANG", CurrencyName = "Netherlands Antillean Guilder" },
            };

            foreach (var c in countries)
            {
                Insert.IntoTable("countries").Row(new
                {
                    name = c.Name,
                    iso2_code = c.Iso2,
                    iso3_code = c.Iso3,
                    phone_code = c.Phone,
                    currency_code = c.Currency,
                    currency_name = c.CurrencyName,
                    is_active = true,
                    created_at = System.DateTime.UtcNow
                });
            }
        }

        public override void Down()
        {
            Delete.FromTable("countries").AllRows();
        }
    }
}
