using FluentMigrator;

namespace DbDeployment.Migrations.Remittance
{
    [Migration(202602240002)]
    public class InsertCountries : Migration
    {
        public override void Up()
        {
            // Bulk insert all countries in a single SQL statement for performance on remote DBs
            Execute.Sql(@"
INSERT INTO countries (name, iso2_code, iso3_code, phone_code, currency_code, currency_name, is_active, created_at) VALUES
('Afghanistan','AF','AFG','+93','AFN','Afghan Afghani',true,NOW()),
('Albania','AL','ALB','+355','ALL','Albanian Lek',true,NOW()),
('Algeria','DZ','DZA','+213','DZD','Algerian Dinar',true,NOW()),
('Andorra','AD','AND','+376','EUR','Euro',true,NOW()),
('Angola','AO','AGO','+244','AOA','Angolan Kwanza',true,NOW()),
('Antigua and Barbuda','AG','ATG','+1-268','XCD','East Caribbean Dollar',true,NOW()),
('Argentina','AR','ARG','+54','ARS','Argentine Peso',true,NOW()),
('Armenia','AM','ARM','+374','AMD','Armenian Dram',true,NOW()),
('Australia','AU','AUS','+61','AUD','Australian Dollar',true,NOW()),
('Austria','AT','AUT','+43','EUR','Euro',true,NOW()),
('Azerbaijan','AZ','AZE','+994','AZN','Azerbaijani Manat',true,NOW()),
('Bahamas','BS','BHS','+1-242','BSD','Bahamian Dollar',true,NOW()),
('Bahrain','BH','BHR','+973','BHD','Bahraini Dinar',true,NOW()),
('Bangladesh','BD','BGD','+880','BDT','Bangladeshi Taka',true,NOW()),
('Barbados','BB','BRB','+1-246','BBD','Barbadian Dollar',true,NOW()),
('Belarus','BY','BLR','+375','BYN','Belarusian Ruble',true,NOW()),
('Belgium','BE','BEL','+32','EUR','Euro',true,NOW()),
('Belize','BZ','BLZ','+501','BZD','Belize Dollar',true,NOW()),
('Benin','BJ','BEN','+229','XOF','West African CFA Franc',true,NOW()),
('Bhutan','BT','BTN','+975','BTN','Bhutanese Ngultrum',true,NOW()),
('Bolivia','BO','BOL','+591','BOB','Bolivian Boliviano',true,NOW()),
('Bosnia and Herzegovina','BA','BIH','+387','BAM','Bosnia-Herzegovina Convertible Mark',true,NOW()),
('Botswana','BW','BWA','+267','BWP','Botswanan Pula',true,NOW()),
('Brazil','BR','BRA','+55','BRL','Brazilian Real',true,NOW()),
('Brunei','BN','BRN','+673','BND','Brunei Dollar',true,NOW()),
('Bulgaria','BG','BGR','+359','BGN','Bulgarian Lev',true,NOW()),
('Burkina Faso','BF','BFA','+226','XOF','West African CFA Franc',true,NOW()),
('Burundi','BI','BDI','+257','BIF','Burundian Franc',true,NOW()),
('Cabo Verde','CV','CPV','+238','CVE','Cape Verdean Escudo',true,NOW()),
('Cambodia','KH','KHM','+855','KHR','Cambodian Riel',true,NOW()),
('Cameroon','CM','CMR','+237','XAF','Central African CFA Franc',true,NOW()),
('Canada','CA','CAN','+1','CAD','Canadian Dollar',true,NOW()),
('Central African Republic','CF','CAF','+236','XAF','Central African CFA Franc',true,NOW()),
('Chad','TD','TCD','+235','XAF','Central African CFA Franc',true,NOW()),
('Chile','CL','CHL','+56','CLP','Chilean Peso',true,NOW()),
('China','CN','CHN','+86','CNY','Chinese Yuan',true,NOW()),
('Colombia','CO','COL','+57','COP','Colombian Peso',true,NOW()),
('Comoros','KM','COM','+269','KMF','Comorian Franc',true,NOW()),
('Congo (DRC)','CD','COD','+243','CDF','Congolese Franc',true,NOW()),
('Congo (Republic)','CG','COG','+242','XAF','Central African CFA Franc',true,NOW()),
('Costa Rica','CR','CRI','+506','CRC','Costa Rican Colon',true,NOW()),
('Croatia','HR','HRV','+385','EUR','Euro',true,NOW()),
('Cuba','CU','CUB','+53','CUP','Cuban Peso',true,NOW()),
('Cyprus','CY','CYP','+357','EUR','Euro',true,NOW()),
('Czech Republic','CZ','CZE','+420','CZK','Czech Koruna',true,NOW()),
('Denmark','DK','DNK','+45','DKK','Danish Krone',true,NOW()),
('Djibouti','DJ','DJI','+253','DJF','Djiboutian Franc',true,NOW()),
('Dominica','DM','DMA','+1-767','XCD','East Caribbean Dollar',true,NOW()),
('Dominican Republic','DO','DOM','+1-809','DOP','Dominican Peso',true,NOW()),
('Ecuador','EC','ECU','+593','USD','US Dollar',true,NOW()),
('Egypt','EG','EGY','+20','EGP','Egyptian Pound',true,NOW()),
('El Salvador','SV','SLV','+503','USD','US Dollar',true,NOW()),
('Equatorial Guinea','GQ','GNQ','+240','XAF','Central African CFA Franc',true,NOW()),
('Eritrea','ER','ERI','+291','ERN','Eritrean Nakfa',true,NOW()),
('Estonia','EE','EST','+372','EUR','Euro',true,NOW()),
('Eswatini','SZ','SWZ','+268','SZL','Swazi Lilangeni',true,NOW()),
('Ethiopia','ET','ETH','+251','ETB','Ethiopian Birr',true,NOW()),
('Fiji','FJ','FJI','+679','FJD','Fijian Dollar',true,NOW()),
('Finland','FI','FIN','+358','EUR','Euro',true,NOW()),
('France','FR','FRA','+33','EUR','Euro',true,NOW()),
('Gabon','GA','GAB','+241','XAF','Central African CFA Franc',true,NOW()),
('Gambia','GM','GMB','+220','GMD','Gambian Dalasi',true,NOW()),
('Georgia','GE','GEO','+995','GEL','Georgian Lari',true,NOW()),
('Germany','DE','DEU','+49','EUR','Euro',true,NOW()),
('Ghana','GH','GHA','+233','GHS','Ghanaian Cedi',true,NOW()),
('Greece','GR','GRC','+30','EUR','Euro',true,NOW()),
('Grenada','GD','GRD','+1-473','XCD','East Caribbean Dollar',true,NOW()),
('Guatemala','GT','GTM','+502','GTQ','Guatemalan Quetzal',true,NOW()),
('Guinea','GN','GIN','+224','GNF','Guinean Franc',true,NOW()),
('Guinea-Bissau','GW','GNB','+245','XOF','West African CFA Franc',true,NOW()),
('Guyana','GY','GUY','+592','GYD','Guyanese Dollar',true,NOW()),
('Haiti','HT','HTI','+509','HTG','Haitian Gourde',true,NOW()),
('Honduras','HN','HND','+504','HNL','Honduran Lempira',true,NOW()),
('Hungary','HU','HUN','+36','HUF','Hungarian Forint',true,NOW()),
('Iceland','IS','ISL','+354','ISK','Icelandic Krona',true,NOW()),
('India','IN','IND','+91','INR','Indian Rupee',true,NOW()),
('Indonesia','ID','IDN','+62','IDR','Indonesian Rupiah',true,NOW()),
('Iran','IR','IRN','+98','IRR','Iranian Rial',true,NOW()),
('Iraq','IQ','IRQ','+964','IQD','Iraqi Dinar',true,NOW()),
('Ireland','IE','IRL','+353','EUR','Euro',true,NOW()),
('Israel','IL','ISR','+972','ILS','Israeli New Shekel',true,NOW()),
('Italy','IT','ITA','+39','EUR','Euro',true,NOW()),
('Ivory Coast','CI','CIV','+225','XOF','West African CFA Franc',true,NOW()),
('Jamaica','JM','JAM','+1-876','JMD','Jamaican Dollar',true,NOW()),
('Japan','JP','JPN','+81','JPY','Japanese Yen',true,NOW()),
('Jordan','JO','JOR','+962','JOD','Jordanian Dinar',true,NOW()),
('Kazakhstan','KZ','KAZ','+7','KZT','Kazakhstani Tenge',true,NOW()),
('Kenya','KE','KEN','+254','KES','Kenyan Shilling',true,NOW()),
('Kiribati','KI','KIR','+686','AUD','Australian Dollar',true,NOW()),
('Kuwait','KW','KWT','+965','KWD','Kuwaiti Dinar',true,NOW()),
('Kyrgyzstan','KG','KGZ','+996','KGS','Kyrgystani Som',true,NOW()),
('Laos','LA','LAO','+856','LAK','Lao Kip',true,NOW()),
('Latvia','LV','LVA','+371','EUR','Euro',true,NOW()),
('Lebanon','LB','LBN','+961','LBP','Lebanese Pound',true,NOW()),
('Lesotho','LS','LSO','+266','LSL','Lesotho Loti',true,NOW()),
('Liberia','LR','LBR','+231','LRD','Liberian Dollar',true,NOW()),
('Libya','LY','LBY','+218','LYD','Libyan Dinar',true,NOW()),
('Liechtenstein','LI','LIE','+423','CHF','Swiss Franc',true,NOW()),
('Lithuania','LT','LTU','+370','EUR','Euro',true,NOW()),
('Luxembourg','LU','LUX','+352','EUR','Euro',true,NOW()),
('Madagascar','MG','MDG','+261','MGA','Malagasy Ariary',true,NOW()),
('Malawi','MW','MWI','+265','MWK','Malawian Kwacha',true,NOW()),
('Malaysia','MY','MYS','+60','MYR','Malaysian Ringgit',true,NOW()),
('Maldives','MV','MDV','+960','MVR','Maldivian Rufiyaa',true,NOW()),
('Mali','ML','MLI','+223','XOF','West African CFA Franc',true,NOW()),
('Malta','MT','MLT','+356','EUR','Euro',true,NOW()),
('Marshall Islands','MH','MHL','+692','USD','US Dollar',true,NOW()),
('Mauritania','MR','MRT','+222','MRU','Mauritanian Ouguiya',true,NOW()),
('Mauritius','MU','MUS','+230','MUR','Mauritian Rupee',true,NOW()),
('Mexico','MX','MEX','+52','MXN','Mexican Peso',true,NOW()),
('Micronesia','FM','FSM','+691','USD','US Dollar',true,NOW()),
('Moldova','MD','MDA','+373','MDL','Moldovan Leu',true,NOW()),
('Monaco','MC','MCO','+377','EUR','Euro',true,NOW()),
('Mongolia','MN','MNG','+976','MNT','Mongolian Tugrik',true,NOW()),
('Montenegro','ME','MNE','+382','EUR','Euro',true,NOW()),
('Morocco','MA','MAR','+212','MAD','Moroccan Dirham',true,NOW()),
('Mozambique','MZ','MOZ','+258','MZN','Mozambican Metical',true,NOW()),
('Myanmar','MM','MMR','+95','MMK','Myanmar Kyat',true,NOW()),
('Namibia','NA','NAM','+264','NAD','Namibian Dollar',true,NOW()),
('Nauru','NR','NRU','+674','AUD','Australian Dollar',true,NOW()),
('Nepal','NP','NPL','+977','NPR','Nepalese Rupee',true,NOW()),
('Netherlands','NL','NLD','+31','EUR','Euro',true,NOW()),
('New Zealand','NZ','NZL','+64','NZD','New Zealand Dollar',true,NOW()),
('Nicaragua','NI','NIC','+505','NIO','Nicaraguan Cordoba',true,NOW()),
('Niger','NE','NER','+227','XOF','West African CFA Franc',true,NOW()),
('Nigeria','NG','NGA','+234','NGN','Nigerian Naira',true,NOW()),
('North Korea','KP','PRK','+850','KPW','North Korean Won',true,NOW()),
('North Macedonia','MK','MKD','+389','MKD','Macedonian Denar',true,NOW()),
('Norway','NO','NOR','+47','NOK','Norwegian Krone',true,NOW()),
('Oman','OM','OMN','+968','OMR','Omani Rial',true,NOW()),
('Pakistan','PK','PAK','+92','PKR','Pakistani Rupee',true,NOW()),
('Palau','PW','PLW','+680','USD','US Dollar',true,NOW()),
('Palestine','PS','PSE','+970','ILS','Israeli New Shekel',true,NOW()),
('Panama','PA','PAN','+507','PAB','Panamanian Balboa',true,NOW()),
('Papua New Guinea','PG','PNG','+675','PGK','Papua New Guinean Kina',true,NOW()),
('Paraguay','PY','PRY','+595','PYG','Paraguayan Guarani',true,NOW()),
('Peru','PE','PER','+51','PEN','Peruvian Sol',true,NOW()),
('Philippines','PH','PHL','+63','PHP','Philippine Peso',true,NOW()),
('Poland','PL','POL','+48','PLN','Polish Zloty',true,NOW()),
('Portugal','PT','PRT','+351','EUR','Euro',true,NOW()),
('Qatar','QA','QAT','+974','QAR','Qatari Riyal',true,NOW()),
('Romania','RO','ROU','+40','RON','Romanian Leu',true,NOW()),
('Russia','RU','RUS','+7','RUB','Russian Ruble',true,NOW()),
('Rwanda','RW','RWA','+250','RWF','Rwandan Franc',true,NOW()),
('Saint Kitts and Nevis','KN','KNA','+1-869','XCD','East Caribbean Dollar',true,NOW()),
('Saint Lucia','LC','LCA','+1-758','XCD','East Caribbean Dollar',true,NOW()),
('Saint Vincent and the Grenadines','VC','VCT','+1-784','XCD','East Caribbean Dollar',true,NOW()),
('Samoa','WS','WSM','+685','WST','Samoan Tala',true,NOW()),
('San Marino','SM','SMR','+378','EUR','Euro',true,NOW()),
('Sao Tome and Principe','ST','STP','+239','STN','Sao Tome and Principe Dobra',true,NOW()),
('Saudi Arabia','SA','SAU','+966','SAR','Saudi Riyal',true,NOW()),
('Senegal','SN','SEN','+221','XOF','West African CFA Franc',true,NOW()),
('Serbia','RS','SRB','+381','RSD','Serbian Dinar',true,NOW()),
('Seychelles','SC','SYC','+248','SCR','Seychellois Rupee',true,NOW()),
('Sierra Leone','SL','SLE','+232','SLL','Sierra Leonean Leone',true,NOW()),
('Singapore','SG','SGP','+65','SGD','Singapore Dollar',true,NOW()),
('Slovakia','SK','SVK','+421','EUR','Euro',true,NOW()),
('Slovenia','SI','SVN','+386','EUR','Euro',true,NOW()),
('Solomon Islands','SB','SLB','+677','SBD','Solomon Islands Dollar',true,NOW()),
('Somalia','SO','SOM','+252','SOS','Somali Shilling',true,NOW()),
('South Africa','ZA','ZAF','+27','ZAR','South African Rand',true,NOW()),
('South Korea','KR','KOR','+82','KRW','South Korean Won',true,NOW()),
('South Sudan','SS','SSD','+211','SSP','South Sudanese Pound',true,NOW()),
('Spain','ES','ESP','+34','EUR','Euro',true,NOW()),
('Sri Lanka','LK','LKA','+94','LKR','Sri Lankan Rupee',true,NOW()),
('Sudan','SD','SDN','+249','SDG','Sudanese Pound',true,NOW()),
('Suriname','SR','SUR','+597','SRD','Surinamese Dollar',true,NOW()),
('Sweden','SE','SWE','+46','SEK','Swedish Krona',true,NOW()),
('Switzerland','CH','CHE','+41','CHF','Swiss Franc',true,NOW()),
('Syria','SY','SYR','+963','SYP','Syrian Pound',true,NOW()),
('Taiwan','TW','TWN','+886','TWD','New Taiwan Dollar',true,NOW()),
('Tajikistan','TJ','TJK','+992','TJS','Tajikistani Somoni',true,NOW()),
('Tanzania','TZ','TZA','+255','TZS','Tanzanian Shilling',true,NOW()),
('Thailand','TH','THA','+66','THB','Thai Baht',true,NOW()),
('Timor-Leste','TL','TLS','+670','USD','US Dollar',true,NOW()),
('Togo','TG','TGO','+228','XOF','West African CFA Franc',true,NOW()),
('Tonga','TO','TON','+676','TOP','Tongan Paanga',true,NOW()),
('Trinidad and Tobago','TT','TTO','+1-868','TTD','Trinidad and Tobago Dollar',true,NOW()),
('Tunisia','TN','TUN','+216','TND','Tunisian Dinar',true,NOW()),
('Turkey','TR','TUR','+90','TRY','Turkish Lira',true,NOW()),
('Turkmenistan','TM','TKM','+993','TMT','Turkmenistani Manat',true,NOW()),
('Tuvalu','TV','TUV','+688','AUD','Australian Dollar',true,NOW()),
('Uganda','UG','UGA','+256','UGX','Ugandan Shilling',true,NOW()),
('Ukraine','UA','UKR','+380','UAH','Ukrainian Hryvnia',true,NOW()),
('United Arab Emirates','AE','ARE','+971','AED','UAE Dirham',true,NOW()),
('United Kingdom','GB','GBR','+44','GBP','British Pound',true,NOW()),
('United States','US','USA','+1','USD','US Dollar',true,NOW()),
('Uruguay','UY','URY','+598','UYU','Uruguayan Peso',true,NOW()),
('Uzbekistan','UZ','UZB','+998','UZS','Uzbekistani Som',true,NOW()),
('Vanuatu','VU','VUT','+678','VUV','Vanuatu Vatu',true,NOW()),
('Vatican City','VA','VAT','+379','EUR','Euro',true,NOW()),
('Venezuela','VE','VEN','+58','VES','Venezuelan Bolivar',true,NOW()),
('Vietnam','VN','VNM','+84','VND','Vietnamese Dong',true,NOW()),
('Yemen','YE','YEM','+967','YER','Yemeni Rial',true,NOW()),
('Zambia','ZM','ZMB','+260','ZMW','Zambian Kwacha',true,NOW()),
('Zimbabwe','ZW','ZWE','+263','ZWL','Zimbabwean Dollar',true,NOW()),
('Hong Kong','HK','HKG','+852','HKD','Hong Kong Dollar',true,NOW()),
('Macau','MO','MAC','+853','MOP','Macanese Pataca',true,NOW()),
('Puerto Rico','PR','PRI','+1-787','USD','US Dollar',true,NOW()),
('Kosovo','XK','XKX','+383','EUR','Euro',true,NOW()),
('Curacao','CW','CUW','+599','ANG','Netherlands Antillean Guilder',true,NOW())
ON CONFLICT DO NOTHING;
");
        }

        public override void Down()
        {
            Delete.FromTable("countries").AllRows();
        }
    }
}
